return {
	mod_title = { en="PewPew" },
	mod_description = { en="Change ranged weapon sounds and projectile visual effects" },
	line_effects_id = { en="Visual effects" },
	sound_effects_id = { en="Sound effects" },
	-- Projectile (line effect) labels
	lasbeam = { en="Lasbeam" },
	lasbeam_pistol = { en="Lasbeam Pistol" },
	lasbeam_pistol_ads = { en="Lasbeam Pistol ADS" },
	lasbeam_killshot = { en="Lasbeam Killshot" },
	lasbeam_elysian = { en="Lasbeam Elysian" },
	lasbeam_charged = { en="Lasbeam Charged" },
	lasbeam_bfg = { en="Lasbeam BFG" },
	autogun_bullet = { en="Autogun Bullet" },
	heavy_stubber_bullet = { en="Heavy Stubber Bullet" },
	pellet_trail = { en="Pellet Trail" },
	shotgun_slug_trail = { en="Shotgun Slug Trail" },
	shotgun_incendiary_trail = { en="Shotgun Incendiary Trail" },
	ripper_trail = { en="Ripper Trail" },
	boltshell = { en="Boltshell" },
	plasma_beam = { en="Plasma Beam" },
	-- Weapon labels
	autopistol_p1_m2 = { en=Localize("loc_autopistol_p1_m2") },
	autogun_p2_m2 = { en=Localize("loc_autogun_p2_m2") },
	forcestaff_p2_m2 = { en=Localize("loc_forcestaff_p2_m2") },
	flamer_p1_m1 = { en=Localize("loc_flamer_p1_m1") },
	forcestaff_p2_m1 = { en=Localize("loc_forcestaff_p2_m1") },
	lasgun_p3_m1 = { en=Localize("loc_lasgun_p3_m1") },
	lasgun_p3_m3 = { en=Localize("loc_lasgun_p3_m3") },
	autopistol_p1_m3 = { en=Localize("loc_autopistol_p1_m3") },
	autogun_p2_m1 = { en=Localize("loc_autogun_p2_m1") },
	autogun_p1_m1 = { en=Localize("loc_autogun_p1_m1") },
	ogryn_heavystubber_p1_m2 = { en=Localize("loc_ogryn_heavystubber_p1_m2") },
	ogryn_heavystubber_p1_m1 = { en=Localize("loc_ogryn_heavystubber_p1_m1") },
	lasgun_p3_m2 = { en=Localize("loc_lasgun_p3_m2") },
	autogun_p1_m2 = { en=Localize("loc_autogun_p1_m2") },
	autopistol_p1_m1 = { en=Localize("loc_autopistol_p1_m1") },
	autogun_p2_m3 = { en=Localize("loc_autogun_p2_m3") },
	autogun_p1_m3 = { en=Localize("loc_autogun_p1_m3") },
	ogryn_heavystubber_p1_m3 = { en=Localize("loc_ogryn_heavystubber_p1_m3") },
	forcestaff_p3_m1 = { en=Localize("loc_forcestaff_p3_m1") },
	-- Ranged shooting sfx labels
	weapon_autopistol_auto = { en="Autopistol Auto" },
	autogun_p2_m2_auto = { en=Localize("loc_autogun_p2_m2") .. " Auto" },
	forcestaff_warp_fire = { en="Forcestaff Warp Fire" },
	flamethrower_fire_loop = { en="Flamethrower Fire Loop" },
	lasgun_p3_m1_fire_auto = { en=Localize("loc_lasgun_p3_m1") .. " Fire Auto" },
	lasgun_p3_m3_fire_auto = { en=Localize("loc_lasgun_p3_m3") .. " Fire Auto" },
	autogun_p2_m1_auto = { en=Localize("loc_autogun_p2_m1") .. " Auto" },
	autogun_p1_m1_auto = { en=Localize("loc_autogun_p1_m1") .. " Auto" },
	heavy_stubber_p1_m2_auto = { en=Localize("loc_ogryn_heavystubber_p1_m2") .. " Auto" },
	heavy_stubber_auto = { en=Localize("loc_ogryn_heavystubber_p1_m1") .. " Auto" },
	lasgun_p3_m2_fire_auto = { en=Localize("loc_lasgun_p3_m2") .. " Fire Auto" },
	autogun_p1_m2_auto = { en=Localize("loc_autogun_p1_m2") .. " Auto" },
	autogun_p2_m3_auto = { en=Localize("loc_autogun_p2_m3") .. " Auto" },
	autogun_p1_m3_auto = { en=Localize("loc_autogun_p1_m3") .. " Auto" },
	heavy_stubber_p1_m3_auto = { en=Localize("loc_ogryn_heavystubber_p1_m3") .. " Auto" },
	psyker_chain_lightning = { en="Psyker Chain Lightning" },
	--charging fx
	psyker_chain_lightning_charge = { en="Psyker Chain Lightning Charge" },
	plasmagun_charge = { en="Plasmagun Charge" },
	psyker_headpop_hands = { en="Psyker Headpop Hands" },
	lasgun_p2_m2_charge = { en=Localize("loc_lasgun_p2_m2") .. " Charge" },
	forcestaff_warp_fire_charge_loop = { en="Forcestaff Warp Fire Charge Loop" },
	lasgun_p2_charge = { en="Lasgun P2 Charge" },
	forcestaff_p4_charge_loop = { en="Forcestaff P4 Charge Loop" },
	plasmagun_charge = { en="Plasmagun Charge" },
	lasgun_p2_m3_charge = { en=Localize("loc_lasgun_p2_m3") .. " Charge" },
	weapon_plasmagun_charge_fast = { en="Plasmagun Charge Fast" },
	--psyker smite
	psyker_smite_charge = { en="Psyker Smite Charge" },
	--plasma vent
	weapon_plasma_mech_vent = { en="Plasma Mech Vent" },
	--weapon special loop
	thunder_hammer_powered_loop = { en="Thunder Hammer Powered Loop" },
	force_sword_loop = { en="Force Sword Loop" },
	power_sword_loop = { en="Power Sword Loop" },
	ogryn_power_maul_1h_loop = { en="Ogryn Power Maul 1H Loop" },
}
