return {
	mod_title = { en = "PewPew" },
	mod_description = { en = "Change ranged weapon sounds and projectile visual effects" },
	weapon_to_be_changed = { en = "Sound to be changed" },
	new_ranged_shooting_sfx = { en = "New shooting sound" },
	line_effects_to_be_changed = { en = "Projectile visual to be changed" },
	new_line_effects = { en = "New projectile visual"},
	-- Projectile (line effect) labels
	lasbeam_id = { en = "Lasbeam" },
	lasbeam_pistol_id = { en = "Lasbeam Pistol" },
	lasbeam_pistol_ads_id = { en = "Lasbeam Pistol ADS" },
	lasbeam_killshot_id = { en = "Lasbeam Killshot" },
	lasbeam_elysian_id = { en = "Lasbeam Elysian" },
	lasbeam_charged_id = { en = "Lasbeam Charged" },
	lasbeam_bfg_id = { en = "Lasbeam BFG" },
	autogun_bullet_id = { en = "Autogun Bullet" },
	heavy_stubber_bullet_id = { en = "Heavy Stubber Bullet" },
	pellet_trail_id = { en = "Pellet Trail" },
	shotgun_slug_trail_id = { en = "Shotgun Slug Trail" },
	shotgun_incendiary_trail_id = { en = "Shotgun Incendiary Trail" },
	ripper_trail_id = { en = "Ripper Trail" },
	boltshell_id = { en = "Boltshell" },
	plasma_beam_id = { en = "Plasma Beam" },
	-- Weapon labels
	-- TODO lookup proper localized names
	autopistol_p1_m2_id = { en = "Autopistol P1 M2" },
	autogun_p2_m2_id = { en = "Autogun P2 M2" },
	forcestaff_p2_m2_id = { en = "Force Staff P2 M2" },
	flamer_p1_m1_id = { en = "Flamer P1 M1" },
	forcestaff_p2_m1_id = { en = "Forcestaff P2 M1" },
	lasgun_p3_m1_id = { en = "Lasgun P3 M1" },
	lasgun_p3_m3_id = { en = "Lasgun P3 M3" },
	autopistol_p1_m3_id = { en = "Autopistol P1 M3" },
	autogun_p2_m1_id = { en = "Autogun P2 M1" },
	autogun_p1_m1_id = { en = "Autogun P1 M1" },
	ogryn_heavystubber_p1_m2_id = { en = "Heavy Stubber P1 M2" },
	ogryn_heavystubber_p1_m1_id = { en = "Heavy Stubber P1 M1" },
	lasgun_p3_m2_id = { en = "Lasgun P3 M2" },
	autogun_p1_m2_id = { en = "Autogun P1 M2" },
	autopistol_p1_m1_id = { en = "Autopistol P1 M1" },
	autogun_p2_m3_id = { en = "Autogun P2 M3" },
	autogun_p1_m3_id = { en = "Autogun P1 M3" },
	ogryn_heavystubber_p1_m3_id = { en = "Heavy Stubber P1 M3" },
	forcestaff_p3_m1_id = { en = "Force Staff P3 M1" },
}
